version: '3.1'

services:

  letsencrypt-nginx-container:
    container_name: 'nginx-container'
    image: nginx:1.19
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/conf.d:/etc/nginx/conf.d/:ro
      - /var/www:/var/www
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
